
양우찬 : dncks0421@gmail.com
이영우 : ywlee0528@gmail.com
이주연 : dkfxl95@naver.com
손연희 : shfwy123@naver.com


-- 사용자 계정 생성하는 구문
-- [표현법] CREATE USER 계정명 IDENTIFIED BY 비밀번호;
CREATE USER C##PENSIEVE IDENTIFIED BY PENSIEVE;

 SELECT * FROM DBA_USERS
 WHERE USERNAME = 'C##PENSIEVE';

-- 생성한 사용자 계정에게 최소한의 권한(데이터관리, 접속) 부여
GRANT RESOURCE, CONNECT TO C##PENSIEVE;

-- 테이블이 저장되는 공간인 테이블스페이스 할당
ALTER USER C##PENSIEVE DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
COMMIT;




CREATE TABLE "MEMBER" (
    "MEMBER_NO"   NUMBER(3)       NOT NULL,
    "MEMBER_ID"   VARCHAR2(50)    NOT NULL,
    "MEMBER_PW"   VARCHAR2(50)    NOT NULL,
    "CREATE_DATE" DATE            DEFAULT SYSDATE NOT NULL
);

COMMENT ON TABLE  "MEMBER"               IS '사용자';
COMMENT ON COLUMN "MEMBER"."MEMBER_NO"   IS '사용자번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID"   IS '사용자아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW"   IS '사용자비밀번호';
COMMENT ON COLUMN "MEMBER"."CREATE_DATE" IS '사용자가입일자';

CREATE TABLE "MENU" (
    "MENU_ID"         NUMBER(3)       NOT NULL,
    "MENU_URL"        VARCHAR2(50)    NOT NULL,
    "MENU_NAME"       VARCHAR2(100)   NOT NULL,
    "MENU_LV"         NUMBER(2)       NULL,
    "MENU_PARENT_ID"  NUMBER(3)       NULL
);

COMMENT ON TABLE  "MENU"                   IS '메뉴';
COMMENT ON COLUMN "MENU"."MENU_ID"         IS '메뉴아이디';
COMMENT ON COLUMN "MENU"."MENU_URL"        IS '메뉴주소';
COMMENT ON COLUMN "MENU"."MENU_NAME"       IS '메뉴이름';
COMMENT ON COLUMN "MENU"."MENU_LV"         IS '메뉴레벨';
COMMENT ON COLUMN "MENU"."MENU_PARENT_ID"  IS '메뉴부모아이디';

CREATE TABLE "TODO" (
    "MEMORY_ID" NUMBER(3)   NOT NULL,
    "STR_DATE"  DATE        NULL,
    "END_DATE"  DATE        NULL,
    "SUCC_DATE" DATE        NULL
);

COMMENT ON TABLE  "TODO"             IS '할일목록';
COMMENT ON COLUMN "TODO"."MEMORY_ID" IS '메모리아이디';
COMMENT ON COLUMN "TODO"."STR_DATE"  IS '시작일자';
COMMENT ON COLUMN "TODO"."END_DATE"  IS '종료일자';
COMMENT ON COLUMN "TODO"."SUCC_DATE" IS '성공일자';

CREATE TABLE "MEMORY" (
    "MEMORY_ID"     NUMBER(3)       NOT NULL,
    "CONTENT"       VARCHAR2(4000)  NOT NULL,
    "TITLE"         VARCHAR2(50)    NULL,
    "CREATE_DATE"   DATE            DEFAULT SYSDATE NOT NULL,
    "MODIFY_DATE"   DATE            NULL,
    "CATEGORY"      VARCHAR2(100)   DEFAULT '전체'    NULL,
    "TODO_YN"       VARCHAR2(10)    DEFAULT N   NOT NULL,
    "MEMBER_NO"     NUMBER(3)       NOT NULL
);

COMMENT ON TABLE  "MEMORY"               IS '메모리';
COMMENT ON COLUMN "MEMORY"."MEMORY_ID"   IS '메모리아이디';
COMMENT ON COLUMN "MEMORY"."CONTENT"     IS '저장내용';
COMMENT ON COLUMN "MEMORY"."TITLE"       IS '메모리제목';
COMMENT ON COLUMN "MEMORY"."CREATE_DATE" IS '생성일자';
COMMENT ON COLUMN "MEMORY"."MODIFY_DATE" IS '수정일자';
COMMENT ON COLUMN "MEMORY"."CATEGORY"    IS '메모리카테고리';
COMMENT ON COLUMN "MEMORY"."TODO_YN"     IS '할일목록여부';
COMMENT ON COLUMN "MEMORY"."MEMBER_NO"   IS '사용자번호';

CREATE TABLE "MEMORY_FILE" (
    "MEMORY_FILE_ID"        NUMBER(10)      NOT NULL,
    "FILE_OWNER"            NUMBER(10)      NULL,
    "FILE_RELA_MEMORY_ID"   NUMBER(10)      NULL,
    "FILE_ORIG_NAME"        VARCHAR2(100)   NULL,
    "FILE_RE_NAME"          VARCHAR2(100)   NULL,
    "FILE_CREATE_DATE"      DATE            DEFAULT SYSDATE NOT NULL,
    "FILE_MODIFY_DATE"      DATE            DEFAULT SYSDATE NULL
);

COMMENT ON TABLE  "MEMORY_FILE"                       IS '메모리파일';
COMMENT ON COLUMN "MEMORY_FILE"."MEMORY_FILE_ID"      IS '메모리파일아이디';
COMMENT ON COLUMN "MEMORY_FILE"."FILE_OWNER"          IS '파일소유자';
COMMENT ON COLUMN "MEMORY_FILE"."FILE_RELA_MEMORY_ID" IS '파일관계메모리아이디';
COMMENT ON COLUMN "MEMORY_FILE"."FILE_ORIG_NAME"      IS '파일원본이름';
COMMENT ON COLUMN "MEMORY_FILE"."FILE_RE_NAME"        IS '파일개명이름';
COMMENT ON COLUMN "MEMORY_FILE"."FILE_CREATE_DATE"    IS '파일생성일자';
COMMENT ON COLUMN "MEMORY_FILE"."FILE_MODIFY_DATE"    IS '파일수정일자';


CREATE TABLE "SPECIAL_DATE" (
    "DATE_ID"        NUMBER(3)     NOT NULL,
    "DATE_KIND"      VARCHAR2(10)      NULL,
    "DATE_NAME"      VARCHAR2(50)      NULL,
    "IS_HOLIDAY"     VARCHAR2(3)       NULL,
    "KST"            VARCHAR2(10)      NULL,
    "LOCDATE"        VARCHAR2(12)      NULL,
    "SEQ"            VARCHAR2(5)       NULL,
    "SUN_LONGITUDE"  VARCHAR2(5)       NULL
);

COMMENT ON TABLE  "SPECIAL_DATE"                 IS '특일정보';
COMMENT ON COLUMN "SPECIAL_DATE"."DATE_ID"       IS '특일아이디';
COMMENT ON COLUMN "SPECIAL_DATE"."DATE_KIND"     IS '종류';
COMMENT ON COLUMN "SPECIAL_DATE"."DATE_NAME"     IS '명칭';
COMMENT ON COLUMN "SPECIAL_DATE"."IS_HOLIDAY"    IS '휴일여부';
COMMENT ON COLUMN "SPECIAL_DATE"."KST"           IS '한국표준시간';
COMMENT ON COLUMN "SPECIAL_DATE"."LOCDATE"       IS '날짜';
COMMENT ON COLUMN "SPECIAL_DATE"."SEQ"           IS '순번';
COMMENT ON COLUMN "SPECIAL_DATE"."SUN_LONGITUDE" IS '태양황경도';


CREATE TABLE "SCHEDULE" (
    "MEMORY_ID"     NUMBER(3)       NOT NULL,
    "STR_DATE"      VARCHAR2(25)        NULL,
    "END_DATE"      VARCHAR2(25)        NULL,
    "REPEAT_PRIOD"  VARCHAR2(30)        NULL
);

COMMENT ON TABLE  "SCHEDULE"                IS '일정목록';
COMMENT ON COLUMN "SCHEDULE"."MEMORY_ID"    IS '메모리아이디';
COMMENT ON COLUMN "SCHEDULE"."STR_DATE"     IS '시작일자';
COMMENT ON COLUMN "SCHEDULE"."END_DATE"     IS '종료일자';
COMMENT ON COLUMN "SCHEDULE"."REPEAT_PRIOD" IS '반복기간';


ALTER TABLE "MEMBER"          ADD CONSTRAINT "PK_MEMBER"          PRIMARY KEY ("MEMBER_NO");
ALTER TABLE "MENU"            ADD CONSTRAINT "PK_MENU"            PRIMARY KEY ("MENU_ID");
ALTER TABLE "TODO"            ADD CONSTRAINT "PK_TODO"            PRIMARY KEY ("MEMORY_ID");
ALTER TABLE "MEMORY"          ADD CONSTRAINT "PK_MEMORY"          PRIMARY KEY ("MEMORY_ID");
ALTER TABLE "MEMORY_FILE"     ADD CONSTRAINT "PK_MEMORY_FILE"     PRIMARY KEY ("MEMORY_FILE_ID");
ALTER TABLE "SPECIAL_DATE"    ADD CONSTRAINT "PK_DATE_ID"         PRIMARY KEY ("DATE_ID");
ALTER TABLE "SCHEDULE"        ADD CONSTRAINT "PK_SCHEDULE"        PRIMARY KEY ("MEMORY_ID");


CREATE SEQUENCE SEQ_MEMORY_ID;
CREATE SEQUENCE SEQ_MENU_ID;
CREATE SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMORY_FILE_ID;
CREATE SEQUENCE SEQ_DATE_ID;




